-- SpendScribe Blog Seed Articles
-- Run once: mysql -u your_user -p u509059322_SpendScribe202 < seed_blog_articles.sql
-- All articles target admin_id = 1. Adjust if needed.

INSERT INTO blog_posts (admin_id, title, slug, excerpt, cover_image_url, cover_image_alt, status, content, tags, meta_title, meta_description, meta_keywords, reading_time, created_at, updated_at, published_at) VALUES

-- ============================================================
-- Article 1: 50/30/20 Rule
-- ============================================================
(1,
'The 50/30/20 Budget Rule: The Simplest System That Actually Works',
'50-30-20-budget-rule',
'The 50/30/20 rule splits your after-tax income into three buckets — needs, wants, and savings — giving you a guilt-free budget that requires no spreadsheet expertise.',
'/public/blog/50-30-20.png',
'Person reviewing monthly budget categories on paper',
'published',
'[
  {"type":"paragraph","text":"If you have ever opened a budgeting app, stared at 30 empty categories, and closed it immediately — you are not alone. The 50/30/20 rule exists precisely for that moment. It is the antidote to over-complicated budgeting."},
  {"type":"heading","text":"What Is the 50/30/20 Rule?"},
  {"type":"paragraph","text":"The 50/30/20 rule is a percentage-based budgeting framework popularised by U.S. Senator Elizabeth Warren in her book <em>All Your Worth</em>. It divides your monthly after-tax income into three simple buckets:"},
  {"type":"list","items":["<strong>50% Needs</strong> — rent, groceries, utilities, minimum debt payments, insurance","<strong>30% Wants</strong> — dining out, streaming services, hobbies, travel","<strong>20% Savings & Debt Repayment</strong> — emergency fund, retirement, extra debt payments"]},
  {"type":"heading","text":"Step 1: Calculate Your After-Tax Income"},
  {"type":"paragraph","text":"Start with what actually lands in your bank account each month after taxes and payroll deductions. If you are salaried, this is straightforward. If you are freelance or self-employed, use your average net income from the last three months — and remember to set aside for taxes yourself."},
  {"type":"heading","text":"Step 2: Assign the Percentages"},
  {"type":"paragraph","text":"Multiply your after-tax income by 0.50, 0.30, and 0.20 to get your three budget caps. For example, if you bring home $3,500 per month: Needs cap = $1,750 | Wants cap = $1,050 | Savings cap = $700."},
  {"type":"heading","text":"Step 3: Track — But Keep It Simple"},
  {"type":"paragraph","text":"The rule works best when you check in weekly. You do not need to categorise every coffee purchase. Just log your spending in each of the three buckets. SpendScribe lets you create exactly three budget categories and see at a glance which bucket is running hot."},
  {"type":"heading","text":"What If My Needs Exceed 50%?"},
  {"type":"paragraph","text":"In high cost-of-living cities, needs often run 60–65% of income. That is okay — treat it as a signal, not a failure. The goal is to work toward the 50% threshold over time by increasing income or reducing fixed costs like rent or car payments."},
  {"type":"heading","text":"50/30/20 vs. Zero-Based Budgeting"},
  {"type":"paragraph","text":"Zero-based budgeting assigns every dollar a job, which is powerful but time-intensive. The 50/30/20 rule trades some precision for speed. Use 50/30/20 if you are new to budgeting or just want a quick sanity check. Graduate to zero-based once you have debt to attack or a specific savings goal."},
  {"type":"heading","text":"Common Mistakes to Avoid"},
  {"type":"list","items":["Counting gross income instead of net income — always use take-home pay","Putting subscriptions in Needs instead of Wants — streaming, gym, and music apps are Wants","Forgetting irregular expenses like car registration, birthdays, or vet bills — smooth these into monthly averages"]},
  {"type":"paragraph","text":"The 50/30/20 rule is not perfect, but it is the fastest way to go from no budget to a functioning one. Start this month, revisit in 30 days, and adjust. That simple habit compounds into real financial change."}
]',
'budgeting,savings,personal finance,beginner',
'The 50/30/20 Budget Rule Explained – Simple & Effective | SpendScribe',
'Learn how the 50/30/20 budget rule works, how to apply it to your income, and why it is the simplest budgeting system for beginners and busy people.',
'50/30/20 rule, budget rule, budgeting for beginners, 50 30 20, simple budget, needs wants savings',
7,
NOW(), NOW(), NOW()),

-- ============================================================
-- Article 2: Budgeting on Irregular Income
-- ============================================================
(1,
'How to Budget on Irregular Income: The Freelancer''s Guide',
'how-to-budget-irregular-income',
'Irregular income makes traditional budgeting feel impossible. Here is a system that lets freelancers, contractors, and gig workers build a reliable budget without a steady paycheck.',
'/public/blog/irregular-income.png',
'Freelancer reviewing income on laptop with coffee',
'published',
'[
  {"type":"paragraph","text":"Traditional budget advice assumes you get paid the same amount on the same day every month. For freelancers, contractors, consultants, and gig workers, that assumption falls apart immediately. But budgeting on variable income is absolutely possible — it just requires a different approach."},
  {"type":"heading","text":"The Core Problem With Variable Income Budgeting"},
  {"type":"paragraph","text":"Most budgeting systems tell you to plan spending based on this month''s income. When income swings from $2,000 one month to $5,000 the next, that method creates constant anxiety and fails completely in slow months."},
  {"type":"heading","text":"Step 1: Find Your Baseline Income"},
  {"type":"paragraph","text":"Look at the last 12 months of income. Find the three lowest months. Average those three numbers. That is your baseline — the floor you can reliably plan around. Budget only from this number, even in good months."},
  {"type":"heading","text":"Step 2: Build a Buffer Account"},
  {"type":"paragraph","text":"Open a separate savings account you call your ''Income Smoother''. Every month, deposit your full income into this account. Then pay yourself a fixed ''salary'' equal to your baseline. When you have a great month, the buffer grows. When you have a slow month, the buffer covers the gap."},
  {"type":"heading","text":"Step 3: Create a Lean Budget Based on Your Baseline"},
  {"type":"paragraph","text":"Build your monthly budget around your baseline salary, not your best-case income. Cover essentials first — rent, utilities, groceries, minimum debt payments, taxes. Then allocate the remainder to discretionary spending."},
  {"type":"heading","text":"Step 4: Log Every Payment the Day It Arrives"},
  {"type":"paragraph","text":"With variable income, cash flow awareness is everything. Log each client payment immediately when it hits your account. SpendScribe''s manual entry makes this a 10-second habit. Over time, you build a real picture of your income rhythm — which clients pay early, which pay late, which months tend to be slow."},
  {"type":"heading","text":"Step 5: Budget for Taxes First"},
  {"type":"paragraph","text":"Before allocating a single dollar to spending, set aside 25–30% of each payment for taxes (adjust based on your country and bracket). Move it to a dedicated tax savings account on the same day the payment lands. This money does not exist for spending purposes."},
  {"type":"heading","text":"What About Business Expenses?"},
  {"type":"paragraph","text":"If you freelance or run a side business, track business expenses separately from personal ones. Create a dedicated budget category for professional tools, subscriptions, equipment, and co-working costs. This makes tax time straightforward and prevents lifestyle expenses from hiding behind ''business'' labels."},
  {"type":"heading","text":"The Mindset Shift That Changes Everything"},
  {"type":"paragraph","text":"Stop thinking in monthly income. Think in annual income divided by 12. When you earn $60,000 in a year, your monthly budget is $5,000 — whether you earn it evenly or in lumpy payments. The buffer account is the mechanical tool that makes this mental model real."},
  {"type":"paragraph","text":"Irregular income is not a budgeting handicap. It is a superpower when managed correctly — you have income flexibility that salaried workers do not. Build the system once, and it runs itself."}
]',
'budgeting,freelance,irregular income,self-employed,cash flow',
'How to Budget on Irregular Income – Freelancer''s Guide | SpendScribe',
'Learn how freelancers, contractors, and gig workers can build a reliable budget system even with variable monthly income. Step-by-step guide with practical tools.',
'budget irregular income, freelancer budget, variable income budget, gig worker budgeting, self-employed budget',
8,
NOW(), NOW(), NOW()),

-- ============================================================
-- Article 3: Digital Envelope Budgeting
-- ============================================================
(1,
'Envelope Budgeting Without Cash: The Digital Method That Actually Works',
'envelope-budgeting-digital',
'The envelope method is one of the most effective budgeting systems ever created. Here is how to use it digitally — no cash, no physical envelopes, no bank connection required.',
'/public/blog/envelope-budget.png',
'Budget envelopes and coins representing spending categories',
'published',
'[
  {"type":"paragraph","text":"The envelope budgeting method is older than credit cards. You take your paycheck in cash, split it into labelled envelopes — one for groceries, one for rent, one for fuel — and when an envelope is empty, spending in that category stops. Simple. Effective. Proven."},
  {"type":"paragraph","text":"The problem: carrying cash and physical envelopes in 2026 is impractical. But the system''s core logic — pre-allocating money to categories before you spend it — is timeless. Here is how to replicate it digitally without connecting a bank account."},
  {"type":"heading","text":"How Digital Envelope Budgeting Works"},
  {"type":"paragraph","text":"Instead of physical envelopes, you create budget categories with a fixed monthly cap. At the start of each month you ''fill'' each category based on your income. As you spend, you log expenses against the relevant category. When the balance hits zero, you stop — or you consciously decide to borrow from another envelope."},
  {"type":"heading","text":"Step 1: List Your Spending Categories"},
  {"type":"paragraph","text":"Start with 6–10 categories. Fewer is better. Common ones include: Housing, Groceries, Transport, Dining Out, Entertainment, Health, Personal Care, Clothing, Savings, Miscellaneous."},
  {"type":"heading","text":"Step 2: Assign a Monthly Cap to Each Category"},
  {"type":"paragraph","text":"Base your caps on the last 2–3 months of actual spending, not wishful thinking. If you regularly spend $400 on groceries, budgeting $200 will not work — it will just make you feel guilty. Set realistic caps, then tighten gradually each month."},
  {"type":"heading","text":"Step 3: Log Every Expense Immediately"},
  {"type":"paragraph","text":"The envelope method only works if you log expenses as they happen — or within the same day. Delayed logging leads to ''I think I spent around...'' which defeats the system. Keep SpendScribe open on your phone. Log purchases while waiting for your card to process."},
  {"type":"heading","text":"Step 4: Check Your Balances Mid-Month"},
  {"type":"paragraph","text":"On the 15th of each month, check every category balance. This mid-point review is what separates people who finish the month on budget from those who do not. If Dining Out is already 80% spent, you know to cook at home for the rest of the month."},
  {"type":"heading","text":"What to Do When an Envelope Runs Out"},
  {"type":"paragraph","text":"You have two options: stop spending in that category, or transfer the shortfall from a lower-priority envelope. The key is to make it a conscious decision, not a silent overspend that you discover at month end. Log the transfer and note why it happened."},
  {"type":"heading","text":"The Biggest Advantages Over App-Based Auto-Syncing"},
  {"type":"list","items":["You see every transaction because you enter it — no automatic imports that you never review","The friction of manual entry makes you think twice before spending","No bank credentials are ever shared with a third party","Works for cash, card, and online purchases equally"]},
  {"type":"paragraph","text":"The envelope method is not about deprivation. It is about intention. When you decide upfront how much each category gets, you stop making a hundred small spending decisions and make one big intentional one instead."}
]',
'budgeting,envelope method,manual tracking,spending categories',
'Digital Envelope Budgeting: No Cash, No Bank Sync Required | SpendScribe',
'Learn how to use the proven envelope budgeting system digitally in 2026. Manual tracking, no bank connection needed. Step-by-step guide for any income type.',
'envelope budgeting, digital envelope budget, cash envelope system, budget categories, manual budget',
7,
NOW(), NOW(), NOW()),

-- ============================================================
-- Article 4: Monthly Budget Reset Checklist
-- ============================================================
(1,
'The Monthly Budget Reset: A Step-by-Step Checklist to Start Every Month Right',
'monthly-budget-reset-checklist',
'A monthly budget reset takes 20 minutes and sets the financial tone for the entire month. Here is the exact checklist to review your last month and plan the next one.',
'/public/blog/budget-reset.png',
'Person with calendar and notebook doing monthly financial review',
'published',
'[
  {"type":"paragraph","text":"Most people set a budget in January and forget about it by February. The ones who actually stick to their budgets do not have more willpower — they have a reset ritual. A monthly budget reset is a deliberate 20-minute review that closes out the previous month and sets up the next one."},
  {"type":"heading","text":"Why a Monthly Reset Matters"},
  {"type":"paragraph","text":"Every month is different. School holidays, car repairs, a friend''s wedding, a pay rise — life does not repeat in predictable 30-day cycles. A reset acknowledges this and recalibrates your plan accordingly. Without it, you are running last month''s budget in this month''s reality."},
  {"type":"heading","text":"The Checklist"},
  {"type":"heading","text":"1. Review Last Month''s Spending"},
  {"type":"paragraph","text":"Open your budget tracker and look at every category. Which ones went over? Which ones came in under? No judgement — just data. The goal is pattern recognition, not self-criticism."},
  {"type":"heading","text":"2. Calculate Your True Net Savings"},
  {"type":"paragraph","text":"Take last month''s income minus all spending. This is your real savings number, not what you planned to save. Compare it to your target. The gap is what you are working to close."},
  {"type":"heading","text":"3. Identify Non-Recurring Expenses Next Month"},
  {"type":"paragraph","text":"Look at the calendar for the coming month. Are there birthdays, travel plans, annual subscriptions, vehicle registrations, or medical appointments? List them and add them as one-off budget items before the month starts. These are the expenses that blow up a budget because they feel like surprises when they were predictable."},
  {"type":"heading","text":"4. Update Your Income Estimate"},
  {"type":"paragraph","text":"If your income is variable, update your estimate for the coming month based on confirmed invoices or expected payments. If you are salaried, confirm nothing has changed — bonus, pay cut, or side income."},
  {"type":"heading","text":"5. Adjust Category Caps"},
  {"type":"paragraph","text":"Based on what you learned in step one, tighten or loosen category caps. If Groceries went $80 over three months in a row, the cap is wrong — raise it. If Dining Out came in well under, you were either too conservative or genuinely eating at home more — decide which and adjust."},
  {"type":"heading","text":"6. Set One Financial Focus for the Month"},
  {"type":"paragraph","text":"Pick one financial goal to focus on this month: build the emergency fund, pay down the credit card, save for a specific purchase. One focus. Write it at the top of your budget. This becomes the tiebreaker when you are deciding whether to spend or save."},
  {"type":"heading","text":"7. Schedule Your Next Reset"},
  {"type":"paragraph","text":"Put your next monthly reset in your calendar before you close the laptop. Same day each month — the 1st, the 28th, the last Sunday. Consistency matters more than the exact date."},
  {"type":"paragraph","text":"The monthly reset is the single habit that separates people who budget successfully long-term from those who try and quit. It is not glamorous. But 20 minutes once a month in exchange for financial clarity is one of the best investments you can make."}
]',
'budgeting,monthly review,habits,savings,financial planning',
'Monthly Budget Reset Checklist: Start Every Month Right | SpendScribe',
'Use this step-by-step monthly budget reset checklist to review last month''s spending and plan the next one. Takes 20 minutes and builds lasting financial habits.',
'monthly budget reset, budget checklist, monthly financial review, budget planning, reset budget',
6,
NOW(), NOW(), NOW()),

-- ============================================================
-- Article 5: Budgeting as a Couple
-- ============================================================
(1,
'How Couples Can Budget Together Without Fighting About Money',
'budget-as-a-couple',
'Money is the number one cause of relationship conflict. Here is a simple system for couples to align on finances, divide responsibilities, and track spending without resentment.',
'/public/blog/couple-budget.png',
'Couple reviewing budget together at kitchen table',
'published',
'[
  {"type":"paragraph","text":"Money arguments are not really about money. They are about values, control, fairness, and fear. The couples who budget successfully together have not found a magic spreadsheet — they have built a system that accounts for two different people with different spending instincts."},
  {"type":"heading","text":"Start With a Money Date, Not a Money Fight"},
  {"type":"paragraph","text":"Schedule a dedicated time to talk finances — not in the car, not during dinner, not after a stressful day. A ''money date'' is a monthly 30-minute sit-down where both partners are present, unhurried, and focused on the numbers together. This single habit prevents 80% of reactive money arguments."},
  {"type":"heading","text":"The Two-Account + One Shared Account System"},
  {"type":"paragraph","text":"The most friction-free structure for couples: each partner keeps a personal account for individual spending, and both contribute to a shared account for joint expenses. No one has to justify buying shoes or video games from their personal account. Joint bills come from the shared account."},
  {"type":"list","items":["Shared account covers: rent/mortgage, utilities, groceries, household items, shared subscriptions, savings goals","Personal accounts cover: clothing, hobbies, personal care, gifts for the other person, individual entertainment"]},
  {"type":"heading","text":"How to Split Contributions Fairly"},
  {"type":"paragraph","text":"''Fairly'' does not always mean 50/50 — especially when incomes differ significantly. A proportional split based on income is often more equitable. If Partner A earns 60% of household income, they contribute 60% to the shared account. Calculate this at the start of each year and revisit if incomes change."},
  {"type":"heading","text":"Assign a Budget Owner, Not a Budget Boss"},
  {"type":"paragraph","text":"One partner should own the monthly reset and tracking process — not as a controller, but as an administrator. The other partner stays informed and participates in the monthly review. Rotate this role every six months if one partner finds it stressful."},
  {"type":"heading","text":"Create Separate Goals and Shared Goals"},
  {"type":"paragraph","text":"Partners should have individual financial goals (career development fund, personal savings, creative project) alongside shared goals (emergency fund, holiday, home deposit). Seeing both on the same budget makes each person''s priorities visible and respected."},
  {"type":"heading","text":"Handle Spending Differences With a Threshold Rule"},
  {"type":"paragraph","text":"Agree on a threshold — say, $200 — above which either partner must mention the purchase to the other before buying. This is not asking permission. It is keeping each other informed so the budget is not blindsided. Below the threshold, spend freely from personal accounts."},
  {"type":"heading","text":"What to Do When One Partner Is Reluctant"},
  {"type":"paragraph","text":"Start with transparency, not control. Share a simple monthly summary — income, shared expenses, savings rate — without requiring the reluctant partner to do the tracking. Showing them the data is usually more persuasive than asking them to participate. Invite, do not mandate."},
  {"type":"paragraph","text":"Budgeting as a couple is less a financial exercise and more a communication exercise. The numbers are easy. The conversation around them is the work. The couples who do it well are not the ones who agree on everything — they are the ones who have built a safe enough space to disagree productively."}
]',
'budgeting,couples,relationships,money habits,shared finances',
'How Couples Can Budget Together Without Fighting | SpendScribe',
'A practical system for couples to budget together, split expenses fairly, and track spending without resentment. Includes the two-account method and money date guide.',
'couples budgeting, budget together, shared finances, money and relationships, joint budget',
8,
NOW(), NOW(), NOW()),

-- ============================================================
-- Article 6: Net Worth Tracking Without Bank Sync
-- ============================================================
(1,
'How to Track Your Net Worth for Free (No Bank Sync, No Risk)',
'net-worth-tracker-no-bank-sync',
'Knowing your net worth is the single most motivating number in personal finance. Here is how to calculate and track it manually every month — without connecting a single account.',
'/public/blog/net-worth.png',
'Person calculating assets and liabilities in a notebook',
'published',
'[
  {"type":"paragraph","text":"Net worth is the one number that tells the full story of your financial health. Not your salary, not your savings account balance, not your credit score — your net worth. It is what you own minus what you owe. And tracking it monthly is the fastest way to stay motivated about your finances."},
  {"type":"heading","text":"What Is Net Worth?"},
  {"type":"paragraph","text":"Net worth = Total Assets − Total Liabilities. Assets are things you own that have value. Liabilities are debts you owe. A positive net worth means you own more than you owe. A negative net worth — common early in life — simply means debt currently outweighs assets. Tracking it shows you the direction of travel."},
  {"type":"heading","text":"Step 1: List Your Assets"},
  {"type":"paragraph","text":"Go through everything you own that has monetary value:"},
  {"type":"list","items":["Checking and savings account balances","Investment accounts (stocks, ETFs, crypto)","Retirement accounts (401k, IRA, pension value)","Property value (current market estimate)","Vehicle value (use a used-car site for current market value)","Other valuables: jewellery, collectibles, business equity"]},
  {"type":"heading","text":"Step 2: List Your Liabilities"},
  {"type":"list","items":["Mortgage balance outstanding","Car loan balance","Student loan balance","Credit card balances","Personal loans","Any other debt"]},
  {"type":"heading","text":"Step 3: Calculate and Record"},
  {"type":"paragraph","text":"Subtract total liabilities from total assets. Record this number in a notebook, spreadsheet, or your SpendScribe notes section. Date it. That is your baseline."},
  {"type":"heading","text":"How Often Should You Update It?"},
  {"type":"paragraph","text":"Monthly is ideal — it gives you enough data points to see trends without the noise of week-to-week market fluctuations. Do your net worth update on the same day as your monthly budget reset for maximum efficiency."},
  {"type":"heading","text":"Why Manual Tracking Is More Powerful Than Automated"},
  {"type":"paragraph","text":"When you manually enter your asset values and debt balances each month, you engage with the numbers. You notice that your car has depreciated $800 since last month. You notice that your student loan is finally below $20,000. You notice your investment account grew by $1,200. Automated syncing shows you the same data — but because you did not touch it, you do not feel it."},
  {"type":"heading","text":"The Motivating Power of Watching Net Worth Grow"},
  {"type":"paragraph","text":"Early on, net worth growth feels slow. Paying off $200 of credit card debt while living costs consume the rest of your income does not feel transformative. But plotted on a chart over 12 months, the line goes up. That visual proof of progress is what keeps people committed to budgeting when motivation fades."},
  {"type":"heading","text":"No Bank Sync Means No Security Risk"},
  {"type":"paragraph","text":"Every app that syncs your bank account holds credentials or tokens that could be compromised. Manual net worth tracking requires zero shared access. You calculate the numbers yourself from your own accounts and enter them yourself. There is nothing to breach."},
  {"type":"paragraph","text":"Your net worth is your financial scoreboard. You do not need an app with read access to your bank to keep score. A notebook and 10 minutes once a month is all it takes."}
]',
'net worth,savings,manual tracking,financial health,privacy',
'Track Your Net Worth for Free Without Bank Sync | SpendScribe',
'Learn how to calculate and track your net worth manually every month — no bank connection, no security risk, and more motivating than automated tools.',
'net worth tracker, track net worth, calculate net worth, personal net worth, net worth without bank sync',
7,
NOW(), NOW(), NOW());
